# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Two-sample Kolmogorov–Smirnov D statistic (fast)
NULL

ks2_fast <- function(x, y) {
    .Call('_twostepAKSA_ks2_fast', PACKAGE = 'twostepAKSA', x, y)
}

